apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: venkateshdeshpande/java-app:2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"        # 0.1 CPU
            memory: "128Mi"    # 128 MiB RAM
          limits:
            cpu: "500m"        # 0.5 CPU
            memory: "512Mi"    # 512 MiB RAM
